language: scala

before_script:
- openssl aes-256-cbc -K $encrypted_3b82e8952ea4_key -iv $encrypted_3b82e8952ea4_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar zxf secrets.tar.gz
- ls

script:
- |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    sbt 'set isSnapshot := false' 'set version := IO.read(new File("VERSION")).mkString.trim' +publish
  else
    sbt -no-colors test +publishSigned -- -oF
  fi

# Don't build version tags
branches:
  except:
    - /^[0-9]+\.[0-9]{1,2}\.[0-9]{1,2}$/