language: scala

script:
- |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    sbt 'set isSnapshot := false' 'set version := IO.read(new File("VERSION")).mkString.trim' +publish
  else
    sbt -no-colors test -- -oF
  fi

# Don't build version tags
branches:
  except:
    - /^[0-9]+\.[0-9]{1,2}\.[0-9]{1,2}$/